# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ELFF-Parser
version:      0.90
version_from: lib/ELFF/Parser.pm
installdirs:  site
requires:
    Carp:                          1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
